version: '3.8' # Spécifie la version de la syntaxe Docker Compose utilisée.

services: # Définit les services (conteneurs) à déployer.

  cells: # Définition du service "cells", probablement pour Pydio Cells, une solution de partage de fichiers.
    image: pydio/cells:latest # Utilise la dernière version de l'image Docker Pydio Cells.
    environment: # Définit les variables d'environnement pour le conteneur.
      - CELLS_BIND=0.0.0.0:8080 # Lie le service sur tous les interfaces réseau au port 8080.
      - CELLS_EXTERNAL=http://pydio.yourdomain.com # URL externe pour accéder à Cells, à adapter selon le domaine.
      - CELLS_NO_SSL=1 # Désactive le chiffrement SSL, utilisez http.
    volumes: # Montage de volumes pour la persistance des données et des logs.
      - cells-data:/var/cells/data # Pour les données.
      - cells-logs:/var/cells/logs # Pour les logs.
    #ports: # Ports exposés sur l'hôte.
    #  - "8080:8080" # Le port 8080 du conteneur est exposé sur le port 8080 de l'hôte.
    networks: # Réseau Docker auquel le service est attaché.
      - pydio-net # Utilise le réseau personnalisé "pydio-net".
      - proxy-main # Utilise le réseau personnalisé "proxy-main".
    restart: unless-stopped # Politique de redémarrage automatique du conteneur.
    labels:
      - "traefik.enable=true" # Activer le Traefik
      - "traefik.http.routers.cells.entrypoints=web" # L'entrée web
      - "traefik.http.routers.cells.rule=Host(`pydio.${BASE_DOMAIN_NAME}`)" # La regle d'access
      - "traefik.http.services.cells.loadbalancer.server.port=8080" # Le port
      - "traefik.docker.network=proxy-main" # Le reseau

  mysql: # Définition du service MySQL pour la base de données.
    image: mysql:latest # Utilise la dernière version de l'image Docker MySQL.
    environment: # Variables d'environnement pour la configuration de MySQL.
      MYSQL_ROOT_PASSWORD: P@ssw0rd # Mot de passe root pour MySQL.
      MYSQL_DATABASE: pydio # Nom de la base de données à créer.
      MYSQL_USER: pydio # Utilisateur de la base de données.
      MYSQL_PASSWORD: P@ssw0rd # Mot de passe pour l'utilisateur de la base de données.
    volumes: # Montage de volumes pour la persistance des données de MySQL.
      - mysql-data:/var/lib/mysql
    networks:
      - pydio-net # Attaché au même réseau "pydio-net".
    restart: unless-stopped

networks: # Définition des réseaux personnalisés.
  pydio-net: # Nom du réseau.
    driver: bridge # Utilise le pilote de réseau bridge.
  proxy-main:
    external: true

volumes: # Définition des volumes pour la persistance des données.
  cells-data:
  cells-logs:
  mysql-data:
